name: CI/CD pipeline
run-name: Building and deploying my app
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update
          sudo apt-get install -y python3
      - run: |
          python3 -m unittest test_app.py
          
  Build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          username: matveysav
          password: dckr_pat_tYz3r4y5OfcdAqYgINfsCvH_XLk
      - uses: docker/build-push-action@v6
        with:
          push: true
          tags: matveysav/my_app:latest
